# How often in real time to force a client synchronization
sync_rate: 1h

# Threshold times to be considered night
nighttime:
  start: 19:00:00 # 7PM
  end: 4:00:00 # 4AM

# Set to true to have the in-game time be equal to real time
# Setting to true disables all other below functionality
real_time: false

# In-game time of day when the server starts
boot_time: 12:00:00 # Noon

# The in-game time modifier compared to real time
# 1 means that one real second is one in-game second
# 60 means that one real second is one in-game minute
# Can vary based on day and night
modifiers:
  day: 1.0
  night: 1.0
